### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by luminalpark** [kellerkinderDE/devenv-shopware#31]
After manually adding Caddy root certificate 
`sudo cp .devenv/state/caddy/data/caddy/pki/authorities/local/root.crt /usr/local/share/ca-certificates/caddyroot.crt`
`sudo update-ca-certificates`

All request get a ERR_SSL_PROTOCOL_ERROR
Am I missing something?

**Comment by kleinmann** [comment]
@luminalpark It's been a while, thank you for your patience 🙂 Is this still an issue for you with the current configuration?

**Comment by lx-wnk** [comment]
Closed due to inactivity
