### ISSUE TITLE
Enable Configuration of HTTP and HTTPS Ports

### ISSUE THREAD

**Issue by TumTum** [kellerkinderDE/devenv-shopware#73]
**Problem:**
Currently, it's not possible to configure the ports for HTTP and HTTPS within the application. This can lead to conflicts, especially when the application is running on alongside other services that use the same ports.

**Solution:**
We should add an option to adjust the ports for HTTP and HTTPS in the configuration file. This would provide users with the flexibility to customize the ports according to their requirements and ensure there are no port conflicts.

**Additional Information:**
The ability to customize the ports would significantly enhance the application's flexibility and user-friendliness.

**Comment by Wysselbie** [comment]
Thank you very much for initiating this feature! 🙂 

There is an ongoing PR that faces domain handling.
A colleague decided to take this into the PR, since the features are matching well. 👍 

Here is the WIP PR: #51

**Comment by jinnoflife** [comment]
This problem was solved with #80.
