### ISSUE TITLE
Caddy cannot open ports 80 and 443

### ISSUE THREAD

**Issue by jhit** [kellerkinderDE/devenv-shopware#91]
Hello.

I'm new to devenv and I had quite some issues with the fact that processes running under non-privileged user account cannot access ports below 1024.
At least that was my experience on Ubuntu 22.10.

```
11:31:32 caddy.1           | Error: loading initial config: loading new config: http app module: start: listening on :443: listen tcp :443: bind: permission denied
```
For me this was a huge bummer because it took me a lot of time to find the reason why my devenv would not start.
Maybe you could consider to use ports above 1024 like the default setup used in the Shopware documentation. They use port 8000.

**Comment by jinnoflife** [comment]
Hey @jhit thanks for the feedback. Currently, we don't plan to reverse the change regarding the ports.
But we made an attempt to ensure that you're able to use our setup in the future. To achieve this, you can edit your [http](https://github.com/kellerkinderDE/devenv-shopware/wiki/Options#kellerkinderhttpport) and [https](https://github.com/kellerkinderDE/devenv-shopware/wiki/Options#kellerkinderhttpsport) port to your liking.

You can also change most of the other available ports.

Hope that helps

**Comment by jhit** [comment]
Fair enough. But mybe you could at least add a hint in the documentation to help other newcomers.

May I ask why you do not seem to have this issue? Are you using this setup on OSX or in Docker Containers? I have no idea why s.o. else could run this on Linux without having issues.

**Comment by jinnoflife** [comment]
>  But mybe you could at least add a hint in the documentation to help other newcomers.

Thats a good point, I added a hint to the docs via #92

> May I ask why you do not seem to have this issue? Are you using this setup on OSX or in Docker Containers? I have no idea why s.o. else could run this on Linux without having issues.

Seems like that. We are working on MacOS and there hasn't been an error like that.

**Comment by jhit** [comment]
Thank you very much.
