### ISSUE TITLE
error: attribute 'currentSystem' missing while building

### ISSUE THREAD

**Issue by mynetx** [kellerkinderDE/devenv-shopware#94]
The expression `$builtins.currentSystem` is causing a build error for me in this line:
https://github.com/kellerkinderDE/devenv-shopware/blob/1acf3fc42fcc38b59fde0ea854ba5e93a8c529e5/modules/php.nix#L39

```sh
       … while evaluating the option `languages.php.package':

       … while calling anonymous lambda
         at «github:cachix/devenv-nixpkgs/06fb0f1c643aee3ae6838dda3b37ef0abc3c763b»/lib/modules.nix:834:19:
          833|           # Avoid sorting if we don't have to.
          834|           if any (def: def.value._type or "" == "order") defs''.values
             |                   ^
          835|           then sortProperties defs''.values

       error: at /nix/store/ida1cg55rk99w3k2cb3jhk3wpnnnby01-source/modules/php.nix:39:36:
           38|   phpVersion = if builtins.hasAttr "PHP_VERSION" config.env then config.env.PHP_VERSION else cfg.phpVersion;
           39|   package = inputs.phps.packages.${builtins.currentSystem}.${phpVersion};
             |                                    ^
           40|

       error: attribute 'currentSystem' missing

✖ Command produced the following output:


Error:   × Command `/nix/store/pd4793lfa38qk790ij35mrnpdcq7vkh3-nix-2.21-devenv/bin/nix --show-trace --extra-experimental-features nix-command --extra-experimental-features flakes --option warn-dirty
  │ false --option eval-cache false --keep-going --max-jobs 5 print-dev-env --profile /Users/jm/Web/lb/katy/.devenv/gc/shell` failed with with exit code 1

direnv: loading the environment failed
direnv: error exit status 1
```

According to the [Nix Reference](https://nixos.org/manual/nix/stable/language/builtin-constants#builtins-currentSystem), the option would not be available in pure evaluation mode.

They’re discussing this option and a [possible workaround](https://blog.kubukoz.com/flakes-first-steps/#flake-outputs) here.

**Comment by kleinmann** [comment]
Thank you for bringing this up @mynetx! This seems to be a change from devenv 1.0 as mentioned in [this devenv blog post](https://github.com/cachix/devenv/blob/ad5a82f493f016bf4e82fae481b374d943be9560/docs/blog/posts/devenv-v1.0-rewrite-in-rust.md?plain=1#L182).

You can include your own clone of our devenv configuration to check if changing this like in the blog post is all that's needed for compatibility. It might be some time until we're able to update this for devenv 1.0 ourselves, so I'm happy for any PRs 🙂
